/**
 * NEXA Finance - Domain Types & Interfaces
 * All monetary amounts are handled strictly in integer cents (e.g. $10.50 = 1050)
 */

export type AccountType = 'cash' | 'bank' | 'checking' | 'savings' | 'digital_wallet';

export interface Account {
  id: string;
  name: string;
  type: AccountType;
  initialBalanceCents: number;
  initialDate: string; // YYYY-MM-DD
  active: boolean;
  color?: string;
  bankName?: string;
  includeInCashFlow?: boolean;
  currency?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreditCard {
  id: string;
  name: string;
  bank: string;
  creditLimitCents: number;
  currentUsedBalanceCents: number;
  statementClosingDay: number; // 1-31
  paymentDueDay: number; // 1-31
  usualPaymentDay?: number; // 1-31
  color?: string;
  active: boolean;
  createdAt: string;
  updatedAt: string;
}

export type MovementType =
  | 'income'
  | 'expense'
  | 'transfer'
  | 'credit_card_payment'
  | 'installment_payment'
  | 'loan_payment'
  | 'subscription'
  | 'service'
  | 'adjustment';

export type MovementStatus = 'planned' | 'completed' | 'cancelled';

export interface Transaction {
  id: string;
  date: string; // YYYY-MM-DD (effective date)
  expectedDate?: string; // YYYY-MM-DD
  actualDate?: string; // YYYY-MM-DD
  concept: string;
  note?: string;
  categoryId: string;
  type: MovementType;
  amountCents: number;
  // Account or card relationship:
  accountId?: string; // Origin account (bank or cash)
  toAccountId?: string; // For transfers
  creditCardId?: string; // For credit card purchases or payments
  status: MovementStatus;
  origin?: string; // e.g., 'subscription:sub_123', 'installment:inst_456', 'manual'
  recurrenceRule?: string; // e.g. 'none', 'monthly', 'biweekly'
  relatedObligationId?: string;
  relatedInstallmentPurchaseId?: string;
  relatedLoanId?: string;
  isGenerated?: boolean; // Generated by projection engine from recurring rules
  isUnbudgeted?: boolean; // Flagged as unplanned / unbudgeted expense
  plannedAmountCents?: number; // Original expected budget amount for this item
  actualAmountCents?: number; // Actual amount disbursed or collected so far
  partialExecutionNote?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Category {
  id: string;
  name: string;
  type: 'income' | 'expense';
  icon: string; // lucide icon name
  color: string;
  isDefault?: boolean;
}

export interface Budget {
  id: string;
  yearMonth: string; // YYYY-MM
  categoryId: string;
  budgetedAmountCents: number;
}

export interface InstallmentPurchase {
  id: string;
  concept: string;
  purchaseDate: string; // YYYY-MM-DD
  totalAmountCents: number;
  creditCardId: string;
  totalInstallments: number;
  installmentValueCents: number;
  firstPaymentDate: string; // YYYY-MM-DD
  frequency: 'monthly' | 'biweekly';
  paidInstallmentsCount: number;
  remainingInstallmentsCount: number;
  note?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Loan {
  id: string;
  name: string;
  originalAmountCents: number;
  currentPendingBalanceCents: number;
  installmentAmountCents: number;
  frequency: 'monthly' | 'biweekly';
  paymentDay: number; // 1-31
  nextPaymentDate: string; // YYYY-MM-DD
  totalInstallmentsCount: number;
  paidInstallmentsCount: number;
  fromAccountId?: string; // Bank account used for payment
  note?: string;
  createdAt: string;
  updatedAt: string;
}

export interface LoanPayment {
  id: string;
  loanId: string;
  date: string; // YYYY-MM-DD
  amountCents: number;
  type: 'regular' | 'extraordinary_capital';
  accountId?: string;
  note?: string;
  createdAt: string;
}

export interface SubscriptionException {
  paused?: boolean;
  overrideAmountCents?: number;
  overrideDay?: number;
  note?: string;
}

export interface Subscription {
  id: string;
  concept: string;
  amountCents: number;
  billingDay: number; // 1-31
  frequency: 'monthly' | 'annual';
  paymentMethodType: 'account' | 'credit_card';
  paymentMethodId: string; // accountId or creditCardId
  categoryId: string;
  status: 'active' | 'paused' | 'cancelled';
  exceptionsByMonth?: Record<string, SubscriptionException>; // keyed by 'YYYY-MM'
  createdAt: string;
  updatedAt: string;
}

export interface ServiceRecord {
  actualAmountCents?: number;
  actualDate?: string;
  status: 'planned' | 'paid';
  note?: string;
}

export interface ServiceBill {
  id: string;
  company: string;
  serviceName: string;
  budgetedAmountCents: number;
  estimatedDay: number; // 1-31
  paymentMethodType: 'account' | 'credit_card';
  paymentMethodId: string;
  categoryId: string;
  active: boolean;
  monthlyRecords?: Record<string, ServiceRecord>; // keyed by 'YYYY-MM'
  createdAt: string;
  updatedAt: string;
}

export interface InitialPosition {
  startDate: string; // YYYY-MM-DD (e.g. '2026-09-12')
  cashBalanceCents: number;
  bankBalances: Record<string, number>; // accountId -> cents
  creditCardUsedBalances: Record<string, number>; // creditCardId -> cents
  loanPendingBalances: Record<string, number>; // loanId -> cents
  isConfigured: boolean;
}

export interface MonthlyClose {
  id: string; // YYYY-MM
  yearMonth: string; // YYYY-MM
  closedAt: string;
  plannedIncomeCents: number;
  realIncomeCents: number;
  plannedExpenseCents: number;
  realExpenseCents: number;
  plannedSavingsCents: number;
  realSavingsCents: number;
  initialBalanceCents: number;
  finalBalanceCents: number;
  initialDebtCents: number;
  finalDebtCents: number;
  notes?: string;
  isClosed: boolean;
}

export interface AppSettings {
  currency: string;
  currencySymbol: string;
  dateFormat: 'YYYY-MM-DD' | 'DD/MM/YYYY';
  firstDayOfWeek: 0 | 1; // 0 Sunday, 1 Monday
  demoDataLoaded: boolean;
  lastBackupDate?: string;
}

// Financial Engine Output Types
export interface DailyCashFlowItem {
  date: string; // YYYY-MM-DD
  dayOfWeek: string;
  dayNumber: number;
  isToday: boolean;
  isPast: boolean;
  initialBalanceCents: number;
  realInflowsCents: number;
  projectedInflowsCents: number;
  realOutflowsCents: number;
  projectedOutflowsCents: number;
  obligationsCents: number;
  projectedFinalBalanceCents: number;
  realFinalBalanceCents?: number;
  events: Transaction[];
  hasRisk: boolean; // projected balance <= 0
  isTight: boolean; // projected balance is low compared to obligations
}

export interface FinancialAlert {
  id: string;
  type: 'insufficient_funds' | 'tight_liquidity' | 'upcoming_payment' | 'positive_trend' | 'info';
  title: string;
  message: string;
  severity: 'red' | 'orange' | 'yellow' | 'green' | 'blue';
  date?: string;
  actionLabel?: string;
}

export interface ExecutiveSummary {
  currentCashBankBalanceCents: number; // Dinero disponible actualmente
  projectedEndPeriodBalanceCents: number; // Saldo proyectado fin de mes
  periodRealIncomeCents: number;
  periodPlannedIncomeCents: number;
  periodRealExpenseCents: number;
  periodPlannedExpenseCents: number;
  periodRealSavingsCents: number;
  periodPlannedSavingsCents: number;
  committedObligationsNext30DaysCents: number; // Dinero comprometido
  availableAfterCommitmentsCents: number; // Dinero disponible después de compromisos
  totalDebtCents: number; // Tarjetas utilizadas + Préstamos pendientes
  totalCreditCardsUsedCents: number;
  totalCreditLimitCents: number;
  totalLoansPendingCents: number;
  obligationsDueTodayCount: number;
  obligationsDueTodayCents: number;
  obligationsThisWeekCount: number;
  obligationsThisWeekCents: number;
}

export type BudgetStatus = 'savings' | 'on_track' | 'warning' | 'over_budget' | 'unbudgeted' | 'zero_spent';

export interface CategoryBudgetAnalysis {
  category: Category;
  budgetedCents: number; // Monto esperado definido para este gasto/categoría
  realSpentCents: number; // Gasto real confirmado (completed)
  plannedPendingCents: number; // Gasto planificado restante (planned)
  totalProjectedCents: number; // Gasto total proyectado a fin de mes (real + planned)
  savingsCents: number; // Monto ahorrado (si real < presupuestado)
  overrunCents: number; // Monto sobregirado (si real/proyectado > presupuestado)
  varianceCents: number; // budgetedCents - realSpentCents (> 0 = ahorro actual, < 0 = sobregiro)
  projectedVarianceCents: number; // budgetedCents - totalProjectedCents
  percentUsed: number; // % del presupuesto consumido en gasto real
  percentProjected: number; // % del presupuesto consumido proyectado
  status: BudgetStatus;
  statusLabel: string;
  isOverBudget: boolean;
  isUnbudgeted: boolean; // Tuvo gasto pero no tenía presupuesto asignado
  transactions: Transaction[]; // Transacciones asociadas
  realTransactions: Transaction[];
  plannedTransactions: Transaction[];
}

export interface RebalanceSuggestion {
  fromCategoryId: string;
  fromCategoryName: string;
  availableSavingsCents: number;
  toCategoryId: string;
  toCategoryName: string;
  neededCents: number;
}

export interface BudgetAnalysisSummary {
  totalBudgetedCents: number; // Total presupuesto esperado
  totalRealCents: number; // Total gasto real ejecutado
  totalPlannedPendingCents: number; // Total pendiente de ejecutar
  totalProjectedCents: number; // Total estimado al cierre del mes
  grossSavingsCents: number; // Suma de ahorros en partidas con gasto menor al esperado
  grossOverrunCents: number; // Suma de sobregiros en partidas excedidas
  netSavingsCents: number; // Ahorro neto consolidado (grossSavings - grossOverrun - totalUnbudgeted)
  totalUnbudgetedCents: number; // Gastos realizados fuera de presupuesto / imprevistos
  unbudgetedCount: number; // Cantidad de transacciones fuera de presupuesto
  unbudgetedTransactions: Transaction[];
  disciplineRate: number; // % de categorías presupuestadas que no tienen sobregiro
  totalCategoriesWithBudget: number;
  categoriesWithSavingsCount: number;
  categoriesOverBudgetCount: number;
  categoriesAtLimitCount: number;
  daysElapsedInMonth: number;
  totalDaysInMonth: number;
  monthProgressPct: number;
  expectedRunRateCents: number; // Cuánto debería haberse gastado al ritmo lineal
  burnRateDiffCents: number; // Diferencia entre gasto real y ritmo esperado
  rebalanceSuggestions: RebalanceSuggestion[];
}
